version: '3.8'

networks:
  profile:

volumes:
  postgres_data:
  pgadmin4_data:

services:
  app-postgres:
    image: postgres:15-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    hostname: postgres
    networks:
      - profile
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    image: dpage/pgadmin4:7.8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    networks:
      - profile